
spring:
  application:
    name: SpringAdminService

server:
  port: 8094
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka
    register-with-eureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: false